# Generated by Django 5.1.2 on 2024-10-13 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weatherAPI', '0002_weather_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weather',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weather_details', to='weatherAPI.location'),
        ),
    ]
